-- SQLite schema for Translation Memory entries in the CAT/TMS adapter layer.
-- This schema stores immutable TM entries with mandatory client isolation.
--
-- Design decisions:
-- 1. Composite primary key (client_id, source_text): Enforces one translation
--    per source text per client. No duplicate source texts within a client.
-- 2. No surrogate ID: TM entries are identified by their natural key
--    (client + source). This simplifies queries and removes surrogate ID overhead.
-- 3. Immutable by convention: Schema allows updates, but adapter never issues
--    UPDATE or DELETE. TM entries are append-only.
-- 4. No Foreign Keys to projects: Projects are referenced by projectId for
--    provenance tracking, but project table lifecycle is separate. This keeps
--    the schemas decoupled.

-- TM entries table stores source-target translation pairs with full provenance.
-- Each entry is immutable and scoped to a specific client to prevent cross-client
-- contamination.
CREATE TABLE tm_entries (
  -- Client that owns this entry. This is the primary isolation boundary:
  -- entries from one client must never be returned in another client's queries.
  client_id TEXT NOT NULL,

  -- Source language text that serves as the lookup key for exact matching.
  -- Invariant: non-empty after trimming; each client has exactly one translation
  -- per source text. Case-sensitive matching.
  source_text TEXT NOT NULL,

  -- Target language translation for this source text. This is the suggested
  -- translation returned when an exact match is found.
  -- Invariant: non-empty after trimming.
  target_text TEXT NOT NULL,

  -- Project that created this TM entry. Used for provenance tracking:
  -- translators can see which project contributed the match when reviewing
  -- suggestions.
  project_id TEXT NOT NULL,

  -- Snapshot that this entry came from. Enables "what TM state existed at
  -- time X" audit queries: translators can reproduce the exact TM state
  -- during their original translation session if clients later dispute wording.
  snapshot_id TEXT NOT NULL,

  -- Milliseconds since Unix epoch when this entry was created. Used for
  -- chronological ordering and audit trails. Provided by caller (core-domain
  -- or application layer), not generated by adapter.
  created_at_epoch_ms INTEGER NOT NULL,

  -- Composite primary key enforces one translation per (client, source text) pair.
  -- If adapter tries to insert duplicate (same client_id + source_text), constraint
  -- violation occurs. This prevents silent overwrites; caller must decide how to
  -- handle duplicates (e.g. reject, log warning, or update explicitly).
  PRIMARY KEY (client_id, source_text)
);

-- Index for efficient exact-match queries by client and source text.
-- This is the primary query pattern: queryTMExactMatch(clientId, sourceText).
-- Query plan: index seek + table lookup = O(log n) + O(1) row access.
CREATE INDEX idx_tm_entries_client_source ON tm_entries(client_id, source_text);

-- Index for client-scoped listing/export queries (e.g. "show all entries for this client").
-- Enables efficient filtering and bulk operations without full table scan.
CREATE INDEX idx_tm_entries_client_id ON tm_entries(client_id);

-- Index for provenance audit queries (e.g. "all entries from this project").
-- Supports translator audits: "Which translations came from Project X?"
CREATE INDEX idx_tm_entries_project_id ON tm_entries(project_id);

-- Index for temporal queries (e.g. "TM entries created after timestamp X").
-- Supports time-based audits: "What TM state existed at moment X?"
CREATE INDEX idx_tm_entries_created_at ON tm_entries(created_at_epoch_ms);

