// Translation Memory domain types for the CAT/TMS core domain.
// This module defines pure types for TM operations with structural client isolation.
// All types are immutable and enforce business invariants at the type level.
//
// Architecture constraint: This module must NEVER import from adapters, UI, or
// runtime layers. All database queries, file I/O, and side effects belong in
// adapters that call these pure functions.

import type {
  ClientId,
  ProjectId,
  SnapshotId,
} from '../state/domain-entities';

// TMProvenance captures where a TM entry originated from, enabling audit trails
// and defensibility when clients dispute wording or translators need to prove
// they followed TM guidance.
//
// Invariants:
// - All fields are required (no optional provenance); every entry must have
//   complete origin tracking
// - createdAt must be a valid epoch timestamp (>= 0, representing milliseconds
//   since Unix epoch)
// - projectId and snapshotId must reference valid domain entities that exist
//   in the current domain state
//
// Forbidden states:
// - createdAt cannot be in the future (relative to creation context); entries
//   must be created with a timestamp that represents the actual creation time
// - projectId cannot be empty, undefined, or reference a non-existent project
// - snapshotId cannot be empty, undefined, or reference a non-existent snapshot
// - Partial provenance (missing projectId or snapshotId) is not allowed; this
//   breaks auditability requirements
export type TMProvenance = {
  // The project that created this TM entry. This enables tracking which project
  // contributed each translation unit to the TM, supporting project-specific
  // TM management and cleanup.
  readonly projectId: ProjectId;

  // The snapshot this entry came from. This enables precise audit trails:
  // translators can prove what TM match was available at translation time by
  // referencing the exact snapshot state.
  readonly snapshotId: SnapshotId;

  // Explicit creation timestamp in epoch milliseconds. This is passed in at
  // creation time, not generated by the system, ensuring the timestamp
  // represents the actual business event time rather than persistence time.
  //
  // Business intent: enables chronological ordering of entries and supports
  // "what TM entries existed at time X" queries for audit purposes.
  readonly createdAt: number;
};

// ClientScope is a branded type that structurally enforces client isolation at
// the type level. Any function working with TM entries must explicitly operate
// within a client scope, preventing accidental cross-client contamination.
//
// This is a structural enforcement mechanism: the type system prevents mixing
// entries from different clients in the same operation, even if the underlying
// ClientId values are the same string. This catches errors at compile time
// rather than runtime.
//
// Invariants:
// - Must always wrap a valid ClientId (non-empty, references existing client)
// - Cannot be constructed without explicit client context; creation functions
//   must validate the client exists before creating a scope
//
// Forbidden states:
// - Empty or undefined client scope (breaks isolation guarantees)
// - Mixing entries from different client scopes in the same operation (type
//   system prevents this, but runtime checks should also validate)
// - Using a ClientScope with entries whose clientId doesn't match the scope
//   (structural violation of isolation)
export type ClientScope = ClientId & { readonly _tag: 'ClientScope' };

// TMEntry represents a single translation unit (source + target pair) in a
// Translation Memory. Entries are immutable once created and structurally
// scoped to a specific client to prevent cross-client contamination.
//
// This is a pure domain type with no persistence metadata. All fields are
// readonly to enforce immutability: once created, an entry cannot be modified.
// Corrections or updates create new entries rather than mutating existing ones.
//
// Required fields:
// - sourceText: Source language text (non-empty after trimming)
// - targetText: Target language text (non-empty after trimming)
// - clientId: Client that owns this entry (structural isolation enforcement)
// - projectId: Project that created this entry (provenance tracking)
// - snapshotId: Snapshot this entry came from (provenance tracking)
// - createdAt: Explicit creation timestamp in epoch milliseconds
//
// Invariants:
// - sourceText and targetText are non-empty strings after trimming whitespace;
//   empty translations are not valid TM entries
// - clientId, projectId, and snapshotId are valid branded IDs that reference
//   existing domain entities in the current state
// - createdAt is a valid epoch timestamp (>= 0, not in the future relative
//   to creation context)
// - Entry is immutable once created: all fields are readonly and cannot be
//   modified after construction
// - clientId must match the client scope when entry is used in operations;
//   entries cannot be used outside their client's scope
// - All provenance fields (projectId, snapshotId, createdAt) are required;
//   entries without complete provenance break auditability requirements
//
// Forbidden states:
// - Empty sourceText or targetText (after trimming); empty strings are not
//   valid translation units
// - clientId that doesn't match the intended client scope; this violates
//   structural isolation and risks cross-client contamination
// - createdAt in the future (relative to creation context); timestamps must
//   represent actual creation time, not speculative future times
// - Any mutation of entry fields after creation; immutability is enforced by
//   readonly fields, but runtime code must also respect this constraint
// - Entries without explicit provenance (missing projectId, snapshotId, or
//   createdAt); incomplete provenance breaks audit trails and defensibility
// - Entries with clientId that references a non-existent client; all IDs must
//   reference valid domain entities
export type TMEntry = {
  // Source language text of this translation unit. This is the original text
  // that was translated, serving as the lookup key for TM matching operations.
  //
  // Business intent: enables finding existing translations for similar or
  // identical source text, reducing redundant translation work.
  readonly sourceText: string;

  // Target language text of this translation unit. This is the translated
  // content that will be suggested when matching source text is found.
  //
  // Business intent: provides the actual translation that was used in a
  // previous project, enabling reuse of approved translations.
  readonly targetText: string;

  // Client that owns this entry. This field enforces structural client
  // isolation: entries are scoped to a specific client and cannot be used
  // outside that client's context without explicit validation.
  //
  // Business intent: prevents cross-client contamination, protecting client
  // IP and ensuring translators don't accidentally reuse translations from
  // one client in another client's project.
  readonly clientId: ClientId;

  // The project that created this TM entry. This enables tracking which project
  // contributed each translation unit to the TM, supporting project-specific
  // TM management and cleanup.
  //
  // Business intent: enables project-specific TM queries and supports cleanup
  // of entries from archived projects if needed.
  readonly projectId: ProjectId;

  // The snapshot this entry came from. This enables precise audit trails:
  // translators can prove what TM match was available at translation time by
  // referencing the exact snapshot state.
  //
  // Business intent: supports defensibility when clients dispute wording by
  // providing exact provenance of the TM match that was used.
  readonly snapshotId: SnapshotId;

  // Explicit creation timestamp in epoch milliseconds. This is passed in at
  // creation time, not generated by the system, ensuring the timestamp
  // represents the actual business event time rather than persistence time.
  //
  // Business intent: enables chronological ordering of entries and supports
  // "what TM entries existed at time X" queries for audit purposes.
  readonly createdAt: number;
};
